# All hyperparameters would be here

VOCABULARY_MIN_FREQ = 3
EMBEDDING_DIM = 100
WINDOW_SIZE = 5
NUM_NEGATIVE_SAMPLES = 5
LEARNING_RATE = 0.001
EPOCHS = 5
BATCH_SIZE = 512
NEG_SAMPLING_EXP_POWER = 0.75

USE_CHAR_NGRAMS = True
CHAR_NGRAM_RANGE = (3, 6)
USE_WORDS_NGRAMS = True
WORD_NGRAM_RANGE = (1, 2)

OVERLAP = 20
SEED = 42
MINM_CHUNK_SIZE = 200 
MAXM_CHUNK_SIZE = 350

TRAIN_RATIO = 0.85
