# All hyperparameters would be here

VOCABULARY_MIN_FREQ = 5
EMBEDDING_DIM = 150
WINDOW_SIZE = 4
NUM_NEGATIVE_SAMPLES = 5
LEARNING_RATE = 0.001
EPOCHS = 10
BATCH_SIZE = 256
NEG_SAMPLING_EXP_POWER = 0.75

USE_CHAR_NGRAMS = False
CHAR_NGRAM_RANGE = (3, 5)
USE_WORDS_NGRAMS = True
WORD_NGRAM_RANGE = (1, 1)

OVERLAP = 10
SEED = 42
MINM_CHUNK_SIZE = 200
MAXM_CHUNK_SIZE = 350

TRAIN_RATIO = 0.85
